// <auto-generated />
using System;
using BookVault.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookVault.Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251229214506_InicialLimpiaConSemilla")]
    partial class InicialLimpiaConSemilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("BookVault.Domain.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Author = "Gabriel García Márquez",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            IsSynced = false,
                            Isbn = "978-0307474728",
                            LastModified = new DateTime(2025, 12, 29, 16, 45, 5, 428, DateTimeKind.Local).AddTicks(6389),
                            Title = "Cien años de soledad"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Author = "Carlos Ruiz Zafón",
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            IsSynced = false,
                            Isbn = "978-8408163381",
                            LastModified = new DateTime(2025, 12, 29, 16, 45, 5, 431, DateTimeKind.Local).AddTicks(6247),
                            Title = "La sombra del viento"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Author = "Yuval Noah Harari",
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            IsSynced = false,
                            Isbn = "978-8449330643",
                            LastModified = new DateTime(2025, 12, 29, 16, 45, 5, 431, DateTimeKind.Local).AddTicks(6271),
                            Title = "Sapiens: De animales a dioses"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Author = "F. Scott Fitzgerald",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            IsSynced = false,
                            Isbn = "978-0743273565",
                            LastModified = new DateTime(2025, 12, 29, 16, 45, 5, 431, DateTimeKind.Local).AddTicks(6275),
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Author = "James Clear",
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            IsSynced = false,
                            Isbn = "978-0735211292",
                            LastModified = new DateTime(2025, 12, 29, 16, 45, 5, 431, DateTimeKind.Local).AddTicks(6278),
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Author = "George Orwell",
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            IsSynced = false,
                            Isbn = "978-0451524935",
                            LastModified = new DateTime(2025, 12, 29, 16, 45, 5, 431, DateTimeKind.Local).AddTicks(6292),
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Author = "Antoine de Saint-Exupéry",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            IsSynced = false,
                            Isbn = "978-2070612758",
                            LastModified = new DateTime(2025, 12, 29, 16, 45, 5, 431, DateTimeKind.Local).AddTicks(6296),
                            Title = "Le Petit Prince"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Author = "Albert Camus",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            IsSynced = false,
                            Isbn = "978-2070360024",
                            LastModified = new DateTime(2025, 12, 29, 16, 45, 5, 431, DateTimeKind.Local).AddTicks(6299),
                            Title = "L'Étranger"
                        });
                });

            modelBuilder.Entity("BookVault.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Fantasía y Ficción"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Historia y Ciencia"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Clásicos Universales"
                        });
                });

            modelBuilder.Entity("BookVault.Domain.Models.Book", b =>
                {
                    b.HasOne("BookVault.Domain.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookVault.Domain.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
